name: service
namespace: dev
replicaCount: 2

image:
  repository: ""
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

containerPort: 80

config:
  enabled: false
  data: {}

secret:
  enabled: false
  data: {}

probes:
  liveness:
    path: /health
    initialDelaySeconds: 20
    periodSeconds: 10
  readiness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 5
