name: application-service
namespace: application-dev
replicaCount: 2

image:
  repository: 288548446501.dkr.ecr.us-east-1.amazonaws.com/hackathon-application-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3001
  targetPort: 3001

containerPort: 3001

imagePullSecrets:
  - ecr-pull-secret

config:
  enabled: true
  data:
    NODE_ENV: development

secret:
  enabled: false
  data: {}

probes:
  liveness:
    path: /health
    initialDelaySeconds: 20
    periodSeconds: 10
  readiness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 5
