name: patient-service
namespace: patient-dev
replicaCount: 2

image:
  repository: 288548446501.dkr.ecr.us-east-1.amazonaws.com/hackathon-patient-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

containerPort: 3000

config:
  enabled: true
  data:
    NODE_ENV: development

secret:
  enabled: false
  data: {}

probes:
  liveness:
    path: /health
    initialDelaySeconds: 20
    periodSeconds: 10
  readiness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 5
