apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-service-dev
  namespace: argocd
spec:
  project: hackathon-dev
  source:
    repoURL: https://github.com/chaitrabk413/hackathon-usecase.git
    targetRevision: hcl
    path: k8s/dev
    helm:
      valueFiles:
        - application-service/dev-value.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: application-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service-dev
  namespace: argocd
spec:
  project: hackathon-dev
  source:
    repoURL: https://github.com/chaitrabk413/hackathon-usecase.git
    targetRevision: hcl
    path: k8s/dev
    helm:
      valueFiles:
        - order-service/dev-value.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: order-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patient-service-dev
  namespace: argocd
spec:
  project: hackathon-dev
  source:
    repoURL: https://github.com/chaitrabk413/hackathon-usecase.git
    targetRevision: hcl
    path: k8s/dev
    helm:
      valueFiles:
        - patient-service/dev-value.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: patient-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
